import type { Metadata } from 'next'
import './globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import { poppins, roboto, rubik } from './fonts'
import Header from '@/components/header/Header'
import NavBar from '@/components/navbar/NavBar'
config.autoAddCss = false

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Header />
        <NavBar />
        {children}
      </body>
    </html>
  )
}
